"""Expand all 6 fixture JSON files from 5 to 10 sessions by adding P6-P10."""
import json

adtech_sessions = [
    {
        "id": "SES6",
        "study_id": "adtech-creative-optimisation",
        "participant_id": "P6",
        "raw_notes": "P6 — Senior Director of Digital Marketing, Fortune-500 CPG company, 12,000 employees\n\nManages a $40M digital media budget across 18 brands globally. Has a dedicated in-house creative studio of 22 people, a DAM system (Bynder), and agency relationships with three holding company shops.\n\n\"We have every tool in the world and we still have the same problem — getting the right creative spec into the right placement on time. Bynder has 50,000 assets in it and half the time the media team can't find the approved version, let alone the right size.\"\n\nTheir creative workflow has six approval stages. By the time creative is approved, the campaign has often already launched with the previous cycle's assets. She described a situation last quarter where they ran a Christmas campaign in January on YouTube because the approved creative didn't arrive in time and the team didn't want to pause spend.\n\n\"The enterprise tools solve for storage and approval governance. They don't solve for format adaptation. That's still a person with Photoshop.\"\n\nHer team has a full-time role — \"Creative Trafficker\" — whose entire job is resizing and adapting approved creative to platform specs. That role costs approximately $85,000 fully loaded per year. She's asked twice to automate it; both times IT security blocked the API integrations required with the agency systems.\n\n\"I'd pay for a tool that just did the resizing automatically. But it has to integrate with Bynder, and it has to fit inside our vendor approval process, which takes six months minimum. That's the blocker.\"\n\nShe's skeptical that a startup can navigate enterprise procurement. Her last three pilot evaluations — all promising tools — died at the security review stage. \"We're interested in the problem space, but we're probably not your customer until you have an enterprise security certification and an existing integration with Bynder.\"\n\nConfirming on pain severity. Skeptical on addressability for enterprise segment.",
        "summary": "Senior Director at Fortune-500 CPG with a $40M budget and a dedicated creative trafficker role costing ~$85K/year purely for resizing and adapting creative. The pain is real and measurable, but enterprise procurement cycles (6+ months, security review requirements, DAM integration mandates) make them unlikely early adopters. Key insight: confirms pain but challenges the market entry strategy — the mid-market may be the right beachhead before targeting enterprise."
    },
    {
        "id": "SES7",
        "study_id": "adtech-creative-optimisation",
        "participant_id": "P7",
        "raw_notes": "P7 — Head of Paid Social, DTC fitness brand, 200 employees. Recently churned from Celtra (dynamic creative platform) after 14 months.\n\nLeft Celtra three months ago after the platform failed to deliver on its promise of automated creative adaptation. The tool required a full HTML5 template rebuild from their agency — a $45,000 project — before they could unlock the automation features. By the time the templates were done, their creative direction had changed and the templates were obsolete.\n\n\"Celtra promised the world. We spent $45K on the setup and then another $120K on the license before we decided it was never going to work for us. The product wasn't bad — the implementation model was broken.\"\n\nNow running entirely manual process. Three freelancers on Upwork who turn around creative resizes at approximately 6-8 hour turnaround. Cost is about $800/month.\n\n\"It's not scalable but it's predictable. I know what I'm paying and I know what I'm getting.\"\n\nHis core frustration is with tools that oversell the ease of setup. \"Every vendor in this space tells you it's plug-and-play. Then you get into it and there's a six-month implementation. I've been burned twice now. I'd need to see a tool that works in under an hour of setup before I'd even consider piloting it.\"\n\nUses a Notion database to track which creative sizes exist for each campaign. Would pay for the right solution — budget of $2-3K/month — but has a very high bar for 'works out of the box' given prior experience. Wants a self-serve trial before any sales conversation.\n\nStrongly confirming on pain. Strongly challenging on ease-of-adoption claims.",
        "summary": "Head of Paid Social who churned from a $165K enterprise creative platform investment after it failed to deliver automation without a complex implementation. Now using Upwork freelancers for $800/month — functional but unscalable. Provides the clearest articulation of the implementation-complexity failure mode: tools that promise automation but require months of setup before delivering value. Will not engage without a self-serve trial and near-zero setup time."
    },
    {
        "id": "SES8",
        "study_id": "adtech-creative-optimisation",
        "participant_id": "P8",
        "raw_notes": "P8 — VP Finance, mid-market e-commerce retailer, 150 employees. Does not manage creative workflows directly but approves all marketing technology purchases over $5,000.\n\nAgreed to the interview to understand 'what the marketing team keeps asking me to buy.' Has approved three martech tools in the past 18 months and been burned twice — tools that were purchased, underused, and cancelled within 12 months.\n\n\"I look at two things: what is the hard-dollar saving, and what is the implementation risk. Marketing always comes to me with the feature demo. I need someone to model out what it replaces and what it costs to implement.\"\n\nWhen asked about the creative resizing workflow, he pulled up a spreadsheet he'd built to track tool ROI. He calculates the marketing team spends approximately 12 hours per week on creative adaptation tasks across three people. At their fully loaded hourly rate of $65, that's $40,560 annually in labor. The tools they've been asked to buy typically cost $24,000-$60,000/year.\n\n\"The math usually works, but then implementation adds 20-30% on top, and then the team still ends up doing it manually anyway because the tool doesn't quite fit the workflow. So I'm paying for the tool AND the manual labor.\"\n\nHe would approve a tool if: (1) it has a clear payback period under 12 months, (2) implementation cost is capped and contractually guaranteed, and (3) there's a 90-day out clause.\n\n\"I'm not anti-investment. I'm anti-commitment before proof.\"\n\nNeutral on the specific pain (defers to marketing team). Challenging on ROI model and commitment structure.",
        "summary": "VP Finance who controls the martech budget and evaluates purchases through a strict ROI lens — he calculates $40K/year in creative adaptation labor cost but has been burned by tools that didn't reduce the labor. Provides the procurement decision framework: payback under 12 months, capped implementation cost, 90-day out clause, and a paid pilot before annual commitment. Critical insight: the finance buyer cares about what the tool replaces, not what it enables."
    },
    {
        "id": "SES9",
        "study_id": "adtech-creative-optimisation",
        "participant_id": "P9",
        "raw_notes": "P9 — Digital Media Manager, mid-market fashion retailer, based in Amsterdam, 300 employees across EU and UK.\n\nRuns campaigns across Meta, Google, TikTok, Snapchat, and a Netherlands-specific platform (Ster). Managing creative across 6 markets in 4 languages (Dutch, German, French, English). GDPR compliance affects creative personalization — cannot use retargeting pixels that many creative optimization tools depend on.\n\n\"Our biggest creative challenge is not the resize — it's the localization. We have 40 active creative variants per campaign across markets and languages. A resize tool helps maybe 20% of the problem.\"\n\nThe localization workflow involves a translation agency, an internal country manager review, and legal sign-off for financial services language. Each creative cycle takes 12-14 days minimum.\n\n\"By the time everything is approved across markets, the campaign opportunity has often passed.\"\n\nMeta's Advantage+ campaign format has partially helped — she now uses it for prospecting in each market separately, which removes some creative complexity. But it doesn't help with TikTok, Snapchat, or Ster.\n\nHer primary pain is coordination overhead, not technical execution. \"We have the tools — Canva for quick edits, the agency for production. What we don't have is a single place to see which creative is approved for which market and channel. We're running that in a shared Google Sheet.\"\n\nGDPR impact: most 'smart' creative optimization tools require pixel-level data she cannot legally collect for certain user segments. \"Tools built for the US market rarely account for consent management complexity. That rules out probably 60% of the vendors we look at.\"\n\nConfirming on complexity/coordination pain. Challenging on most US-built tools being fit for EU market.",
        "summary": "EU-based media manager running campaigns across 6 markets in 4 languages, where the creative challenge is localization complexity and GDPR consent management rather than simple resizing. US-built tools that depend on retargeting pixels fail EU compliance requirements, ruling out ~60% of vendors she evaluates. Key insight: the international market has a materially different problem definition — localization and consent management are the core issues, not format adaptation."
    },
    {
        "id": "SES10",
        "study_id": "adtech-creative-optimisation",
        "participant_id": "P10",
        "raw_notes": "P10 — Performance Marketing Lead, SaaS company, 180 employees. Has built a semi-automated creative production pipeline using Zapier, Google Sheets, and Bannerbear API.\n\nIdentified the creative resizing problem three years ago when he was spending 8-10 hours per week on it personally. Spent two months building an automation: brief enters a Google Form, triggers a Zapier workflow, which calls Bannerbear API to generate standard banner sizes, then uploads to a shared Dropbox folder with Slack notification.\n\n\"It's not pretty but it works. Reduces my time from 8 hours to maybe 45 minutes per campaign — the 45 minutes is QA and any custom sizes Bannerbear can't handle.\"\n\nCurrent limitations: Bannerbear handles static images but not video. Video still requires manual export from After Effects with 4-5 different size presets.\n\n\"Video is about 40% of our creative budget now, so my automation only solves 60% of the problem.\"\n\nHas looked at all the major tools in this space. Has tried Storyteq (too expensive, £3K/month), Madgicx (focused on targeting, not creative), and Celtra (enterprise implementation burden).\n\n\"I've done the research. Nothing hits the sweet spot of: works for video, affordable for a 180-person company, doesn't require an agency to set up.\"\n\n\"The tool I want doesn't exist yet. It's Bannerbear but with native video support and some basic AI for copy localization. I'd pay $800-1,500/month for that.\"\n\nIs actively evaluating two new entrants in the space. Would switch from his custom solution if the product hit his criteria — and he has the technical chops to evaluate it properly within one sprint.\n\nStrongly confirming on pain. Skeptical because he's tried everything and built his own solution. Provides the clearest product spec of any participant.",
        "summary": "Power user who built his own creative automation pipeline (Zapier + Bannerbear) that saves ~7 hours/week but only covers static image formats — video, animated GIFs, and HTML5 units still require manual work. Has evaluated every tool in the market and found none that solve video + affordability + easy setup. Provides the most precise product spec: video support, sub-$1,500/month, self-serve setup. His criteria and his current workaround define the MVP feature bar better than any other participant."
    }
]

audience_sessions = [
    {
        "id": "SES6",
        "study_id": "audience-segmentation-automation",
        "participant_id": "P6",
        "raw_notes": "P6 — VP Programmatic, enterprise consumer goods company, 8,000 employees. Manages a $60M programmatic budget across 12 brands.\n\nHas a full data science team dedicated to audience modeling and a DMP (Adobe Audience Manager) with CRM integration. Also has identity graph access through LiveRamp and runs custom look-alike models in Python.\n\n\"We've solved the technical problem of audience segmentation. The problem we haven't solved is getting the models into the buying platforms fast enough to matter. There's a 24-48 hour lag between our model outputs and the audience being live in DV360.\"\n\nTheir data science team builds new audience segments weekly; activating them requires an API call sequence through LiveRamp to DV360 that requires manual intervention when segment populations are under threshold.\n\n\"We have 400 active segments across our brands. Managing the lifecycle — refreshing, suppressing, archiving — is a full-time job for two people. The tools don't give you a unified view across brands.\"\n\nPlatform fragmentation is the core operational challenge. Each brand runs independently in Meta, TikTok, Pinterest, and their DSP — audience definitions are inconsistent across platforms.\n\n\"We have 'high-value customer' defined 14 different ways across our brand stack. There's no source of truth.\"\n\nWould not benefit from an SMB audience segmentation tool — already past that stage. What he'd pay for is a segment orchestration layer that manages lifecycle and syncs definitions across platforms. Budget: $10-15K/month at enterprise scale.\n\nConfirming on operational complexity pain. Beyond the scope of most SMB-focused tools in this space.",
        "summary": "Enterprise VP Programmatic with a sophisticated DMP + data science stack who has solved the modeling problem but faces a segment orchestration challenge: 24-48 hour activation lag, inconsistent segment definitions across 14 brand contexts, and a 2-person team managing lifecycle for 400 active segments. Key insight: the enterprise problem is segment operationalization and governance, not creation — a fundamentally different product than mid-market audience building automation."
    },
    {
        "id": "SES7",
        "study_id": "audience-segmentation-automation",
        "participant_id": "P7",
        "raw_notes": "P7 — Director of Performance Marketing, DTC apparel brand, 250 employees. Recently churned from Lotame Spherical (DMP platform) after 18 months.\n\nChurned because Lotame required a pixel implementation on their Shopify store that conflicted with their Consent Management Platform. After 6 months of trying to make it work, they gave up.\n\n\"We were paying $4,000/month for a segment tool we couldn't activate because we couldn't legally collect the data it needed.\"\n\nNow using Meta's native audience tools, Google's Customer Match, and manual cohort analysis in BigQuery. Has accepted that multi-touch is effectively broken for DTC brands post-iOS.\n\n\"Honestly, going first-party has been better for us. Our ROAS from Customer Match audiences is 40% higher than our best third-party segment ever was. But we're only reaching 20% of the people we could reach.\"\n\nThe gap: they have good first-party audiences for existing customers but cannot build meaningful prospecting audiences without third-party data.\n\n\"We have 50,000 customers. Our look-alike audiences cap out at maybe 2M people. We need scale we can't get from first-party alone.\"\n\nWould not go back to a third-party DMP. Is evaluating clean room solutions as an alternative — match existing customers to publisher data without moving data.\n\n\"That's where I think the future is, but the technology isn't ready for a company our size.\"\n\nHis ideal tool: automated first-party audience building from their Shopify + Klaviyo data, with direct sync to Meta and Google — no DMP middleware. \"I'd pay $500-800/month for a Shopify-native tool that automatically builds and syncs custom audiences without me touching the API.\"\n\nStrongly confirming on audience reach limitation. Challenging on third-party data approaches; bullish on first-party native solutions.",
        "summary": "Director who churned from a $4K/month DMP after a compliance conflict made it unusable — and found that going first-party-only actually improved ROAS by 40%, though it capped audience reach. Provides a clear product spec: Shopify-native first-party audience automation with direct Meta/Google sync at $500-800/month. Key reframe: the first-party constraint is a feature for privacy-forward buyers, not just a limitation."
    },
    {
        "id": "SES8",
        "study_id": "audience-segmentation-automation",
        "participant_id": "P8",
        "raw_notes": "P8 — CFO, mid-market e-commerce company, 180 employees. Approves all martech purchases over $3,000/month.\n\nAsked about marketing's audience segmentation spend for the first time six months ago during an annual planning review. Found that the marketing team had three overlapping tools — a DMP, a CDP, and a data append service — totaling $8,400/month. None of the three teams could clearly explain what problem each solved that the others didn't.\n\n\"I consolidated the three tools into one. The marketing team was upset for a month, then admitted they'd been paying for tools that weren't talking to each other anyway.\"\n\nFrom a financial perspective, the ROI case for audience segmentation tools is weak in his experience.\n\n\"Marketing tells me better segmentation improves ROAS. Maybe. But they can never tell me by how much before we buy, and they can never prove it after. The attribution is always murky.\"\n\nWould approve spend on a segmentation tool only if it came with a measurement framework built in — a test vs. control design that demonstrates ROAS lift attributable to the segmentation.\n\n\"Show me a holdout test that proves you're adding value. That's all I need.\"\n\nHas a simple heuristic: if a tool cannot be evaluated on a 90-day pilot with a clear success metric, he doesn't approve it.\n\n\"If you can't agree upfront on what success looks like, you're not ready to buy.\"\n\nNeutral on the specific pain (defers to marketing team). Challenging on ROI demonstrability — this is the gating criterion.",
        "summary": "CFO who consolidated three overlapping audience tools ($8,400/month) after finding they weren't integrated. His approval criterion: a built-in measurement framework that proves ROAS lift via holdout testing, agreed upfront. Critical insight: the finance buyer cares about demonstrable ROI more than features, and requires a structured measurement framework as a purchasing prerequisite."
    },
    {
        "id": "SES9",
        "study_id": "audience-segmentation-automation",
        "participant_id": "P9",
        "raw_notes": "P9 — Head of Digital Marketing, beauty retailer, based in Singapore, 400 employees across APAC.\n\nManages campaigns across Meta, Google, TikTok, Line (Japan and Thailand), and Lazada Sponsored (Southeast Asia). Each platform has a different audience taxonomy and data availability.\n\n\"In APAC we're dealing with 8 platforms across 6 markets that each have their own definition of 'interest' and 'behavior'. There is no unified segmentation — it's impossible.\"\n\nThird-party data quality in Southeast Asia is significantly worse than in the US or EU. Many data providers have poor coverage outside major cities.\n\n\"We've tried 4 data providers for look-alike enrichment in Indonesia. All four were garbage — response rates under 0.1%.\"\n\nHer primary solution: heavy use of first-party CRM data via Customer Match and manual audience creation in each platform separately.\n\n\"We upload the same CRM segment to six platforms manually every week. It takes one person half a day.\"\n\nThe manual sync is the core pain. She's tried automated solutions but they typically cover only Meta + Google, not Line or Lazada.\n\n\"Every tool covers the US platforms. No one has cracked Southeast Asia distribution.\"\n\nWould pay for a tool that automates CRM-to-platform sync across all her markets including Line and Lazada, even if the AI/ML layer was basic.\n\n\"I don't need sophisticated segmentation. I need a reliable pipe from my CRM to my media platforms.\"\n\nConfirming on manual sync pain and first-party-only constraint. Challenging on most Western tools having meaningful APAC platform coverage.",
        "summary": "APAC-based marketer coordinating campaigns across 8 platforms in 6 markets where third-party data quality is poor and manual CRM sync to each platform takes half a person's day weekly. Most commercial tools cover only Meta + Google, missing Line, Lazada, and other APAC-specific platforms. Key insight: the APAC market's primary need is reliable CRM-to-platform piping across a fragmented platform landscape — not sophisticated segmentation logic."
    },
    {
        "id": "SES10",
        "study_id": "audience-segmentation-automation",
        "participant_id": "P10",
        "raw_notes": "P10 — Data Analyst (Marketing), SaaS company, 220 employees. Has built a custom audience sync pipeline using Python, dbt, and the Meta/Google APIs.\n\nSpent three months building an automated pipeline: Salesforce CRM data → dbt transforms in BigQuery → Python script that hashes and uploads to Meta Customer Match and Google Customer Match on a weekly schedule.\n\n\"It works perfectly for our use case. We have 12 audience segments updating automatically every Sunday night. Monday morning the media team has fresh audiences in both platforms without touching anything.\"\n\nCurrent limitations: only covers Meta and Google. LinkedIn, TikTok, and Bing are still manual. The LinkedIn API for audience upload is complex and rate-limited; TikTok's is poorly documented.\n\n\"I've tried to extend the pipeline to LinkedIn four times. Their API is a nightmare.\"\n\nAlso doesn't cover suppression logic — ensuring churned customers are excluded from acquisition campaigns.\n\n\"We still do suppression manually because it's harder to automate the 'who NOT to target' logic across different platform taxonomies.\"\n\nHis honest assessment of commercial tools: \"Most of them are basically doing what I built but with a UI on top. I could replace my pipeline tomorrow for $300-500/month if a tool covered LinkedIn and TikTok natively. That's the only reason I'd switch.\"\n\nHas a very high technical bar for evaluation — will inspect API docs before agreeing to a trial.\n\n\"Don't show me a demo until you've given me your API documentation. I want to know if you're actually handling the platform edge cases or just the happy path.\"\n\nStrongly confirming on pain (has solved 70% of it himself). High bar for switching — only LinkedIn + TikTok native coverage would make him switch from his custom build.",
        "summary": "Data Analyst who built a custom Python/dbt/API pipeline automating audience syncing to Meta and Google but cannot extend it to LinkedIn (API too complex) or TikTok (poor documentation). Would pay $300-500/month for a commercial tool only if it natively supports LinkedIn and TikTok. Will evaluate tool quality via API docs before agreeing to a demo — highest technical sophistication of all participants."
    }
]

attribution_sessions = [
    {
        "id": "SES6",
        "study_id": "attribution-modelling-gaps",
        "participant_id": "P6",
        "raw_notes": "P6 — VP Marketing Analytics, enterprise retail brand, 5,000 employees. Has a dedicated analytics team of 8 people and uses Neustar for marketing mix modeling.\n\nRuns quarterly MMM studies. Has a data clean room agreement with two publishers. Uses Northbeam as a supplementary MTA layer for tactical decision-making between MMM cycles.\n\n\"We know MMM is the gold standard for cross-channel budget allocation at our scale. The problem is it's quarterly. The world changes weekly. So we're using Northbeam to make weekly decisions and MMM to validate quarterly whether we were directionally right.\"\n\nDescribes a two-speed attribution architecture: MMM for strategic allocation, MTA for tactical in-campaign adjustments.\n\n\"The error people make is trying to use one model for both. MMM tells you whether to invest in TV vs. search. MTA tells you whether to shift budget between Meta campaigns.\"\n\nHis team spends approximately $180,000/year on attribution infrastructure (MMM studies + Northbeam license + analyst time).\n\n\"My CFO asked me last quarter to justify the attribution stack spend. The honest answer is: we can't prove the MMM is more accurate than intuition, but we have more confidence in our decisions.\"\n\nThe unresolved challenge is brand investment attribution. \"We spend $8M a year on brand and can't tell you what it does. The halo effects on search and direct aren't cleanly attributable. That's the hole in every attribution model.\"\n\nConfirming on complexity of cross-channel attribution. Beyond the scale most mid-market tools address.",
        "summary": "Enterprise VP Analytics running a two-speed attribution architecture (quarterly MMM for strategic allocation + Northbeam for tactical weekly decisions) at $180K/year investment. Articulates the key insight that using one model for both strategic and tactical decisions is the core failure mode. The unresolved problem even at enterprise scale: brand investment attribution — $8M in brand spend with no clean measurement framework."
    },
    {
        "id": "SES7",
        "study_id": "attribution-modelling-gaps",
        "participant_id": "P7",
        "raw_notes": "P7 — Head of Growth, DTC supplements brand, 120 employees. Churned from Rockerbox (MTA platform) 5 months ago after 10-month contract.\n\nLeft Rockerbox because their pixel coverage degraded after iOS 17 and the platform's response was 'we're working on it' for four months.\n\n\"We were paying $3,000/month for data that was 40% incomplete. At some point you're paying for noise, not signal.\"\n\nNow using GA4 as primary attribution and Meta's own attribution window as a secondary check. Has accepted that multi-touch is effectively broken for DTC brands post-iOS.\n\n\"We stopped trying to do MTA. We now run test and control on every significant channel decision. Incrementality testing is harder to operationalize but the data is real — you're not relying on pixels that may or may not be firing.\"\n\nHas moved their entire measurement approach toward incrementality testing. Uses geo-based holdout tests and time-based holdouts.\n\n\"We've done 6 incrementality tests in the last 8 months. They've changed our budget allocation more than 3 years of MTA data ever did.\"\n\nWould not buy another MTA platform. Would consider a tool that helps design and analyze incrementality tests — specifically automating the geo selection and statistical analysis.\n\n\"The hard part isn't running the holdout. It's knowing which geos to use and whether your lift is statistically significant. A tool that handles that would be valuable.\"\n\nBudget for incrementality testing infrastructure: $1-2K/month. Strongly challenging on MTA as a viable approach post-iOS.",
        "summary": "Head of Growth who churned from Rockerbox after iOS 17 degraded pixel coverage to the point of unusability — and has since moved entirely to incrementality testing using geo and time holdouts. Has run 6 incrementality tests in 8 months that changed budget allocation more than 3 years of MTA data. Provides a clear pivot point: the market is moving from MTA to incrementality testing, and there's a tooling gap in test design and statistical analysis for mid-market teams."
    },
    {
        "id": "SES8",
        "study_id": "attribution-modelling-gaps",
        "participant_id": "P8",
        "raw_notes": "P8 — CFO, mid-market DTC brand, 200 employees. Challenged the marketing team's attribution model during the last three annual planning cycles.\n\n\"Every year marketing comes to me with a channel mix recommendation supported by attribution data. Every year I push back. The model always credits the channel that marketing already wants to invest in.\"\n\nMade the marketing team run a 4-week channel blackout test on display advertising two years ago. Display had been receiving 15% of budget based on attribution. During the blackout, revenue dropped 2% — not the 15% the attribution model implied. Reallocated the display budget to search and saw a 12% revenue improvement.\n\n\"That one test was worth more than three years of attribution modeling. Now I ask for a test before any significant budget shift.\"\n\nHis current expectation: any budget allocation proposal must come with a measurement plan.\n\n\"I won't approve a channel strategy without a measurement plan. That's the policy now.\"\n\nIs interested in tools that facilitate test design, not attribution modeling.\n\n\"I don't trust models. I trust experiments. If your tool helps us run better experiments faster, that's interesting.\"\n\nChallenging on MTA/attribution modeling in general. Strong advocate for experimental measurement approach.",
        "summary": "CFO who distrusts attribution modeling and has formalized a policy that any budget allocation proposal must include a measurement plan with explicit test/control design. His display blackout test showed attribution over-credited display by 7x compared to actual revenue impact. Key insight: the CFO as a buyer cares about experimental proof, not model sophistication — and has institutionalized this as a company policy."
    },
    {
        "id": "SES9",
        "study_id": "attribution-modelling-gaps",
        "participant_id": "P9",
        "raw_notes": "P9 — Performance Marketing Manager, consumer fintech brand, based in Berlin, 400 employees. Running EU campaigns with compounded iOS + GDPR measurement restrictions.\n\nThe attribution problem in Germany is worse than the US equivalent because of two compounding factors: iOS tracking opt-out rates in Germany run approximately 80-85% (vs. 65-70% in the US), and GDPR consent requirements mean their pixel fires on fewer than 40% of site visitors.\n\n\"In Germany, we can properly track maybe 15% of our customer journeys. The rest is dark. Whatever attribution model we run is built on 15% of the data and extrapolated. That's not insight — that's guesswork.\"\n\nTheir response: use modeled conversions (Meta's and Google's own ML fill for unmeasured events) as the primary optimization signal, and validate quarterly with media mix modeling.\n\n\"We've handed the attribution problem back to the platforms. They have access to data we don't — their own first-party signals. Their modeled conversions are probably more accurate than our pixel data.\"\n\nThe practical implication: budgets are set by MMM quarterly and the in-campaign optimization is left entirely to platform algorithms. Human intervention in targeting and creative allocation is minimal.\n\n\"We've removed most of our manual optimization work. It's counterintuitive but our results have improved since we trusted the platforms more.\"\n\nUnresolved: how to evaluate platform performance when the platform is also providing the measurement.\n\n\"There's a conflict of interest problem that nobody has solved well.\"\n\nConfirming on measurement breakdown in privacy-first markets. Challenging on viability of any third-party attribution approach for EU markets.",
        "summary": "EU-based performance marketer in Germany where compounded iOS opt-out (85%) and GDPR consent rates (40%) mean only ~15% of customer journeys are trackable. Response: hand optimization back to platform algorithms using their own modeled conversions, validate quarterly with MMM. Key insight: in high-privacy markets, platform-native ML is more reliable than third-party attribution — a significant challenge to any third-party MTA tool's value proposition."
    },
    {
        "id": "SES10",
        "study_id": "attribution-modelling-gaps",
        "participant_id": "P10",
        "raw_notes": "P10 — Analytics Engineer, performance agency, 80 employees. Has built a custom data-driven attribution model in dbt + BigQuery for 6 of the agency's clients.\n\nSpent 4 months building a Markov chain attribution model that processes raw GA4 event data, applies channel weighting based on position in the customer journey, and outputs channel credit scores to a Looker Studio dashboard.\n\n\"The model is technically sound. The problem is explainability. I can tell a client their social spending is 23% more efficient than the model implies on last-click, but I can't explain to them in 30 seconds why. Attribution models are inherently hard to communicate.\"\n\nRuns the model for 6 clients at approximately 8 hours/month of maintenance per client. Revenue: the agency charges $1,500/month per client for attribution analysis. Total: $9,000/month recurring.\n\n\"It's become a real revenue line for us.\"\n\nThe limitation: his model only uses GA4 data, which has the same iOS blind spots as any pixel-based approach.\n\n\"I'm building a sophisticated model on incomplete data. It's directionally useful but I'd never claim the numbers are precise.\"\n\nLooking at whether to productize the model into an agency-sold tool or find a commercial partner to white-label.\n\n\"If someone built a dbt-native attribution model that I could customize for each client, I'd recommend it to all of them and probably stop maintaining my own.\"\n\nHas been evaluating Meridian (Google's open-source MMM) as a potential replacement for the custom model.\n\nStrongly confirming on the mid-market attribution gap. Would switch from custom build if a dbt-native commercial solution existed.",
        "summary": "Analytics Engineer who built a custom Markov chain attribution model generating $9,000/month in agency revenue — proving mid-market clients will pay for something better than last-click attribution. The core problem is explainability: the model is technically sound but hard to communicate to non-technical clients. Would switch to a commercial dbt-native solution that handles per-client customization. Has also evaluated open-source MMM (Google Meridian) as a replacement."
    }
]

pacing_sessions = [
    {
        "id": "SES6",
        "study_id": "campaign-pacing-optimisation",
        "participant_id": "P6",
        "raw_notes": "P6 — VP Programmatic Trading, holding company agency, 1,200 employees. Manages pacing for a portfolio of 40+ clients, total media under management $120M.\n\nHas a dedicated trading desk with 12 programmatic traders. Each trader manages 8-12 clients simultaneously. Pacing is checked three times daily via a custom dashboard built on DV360 API + Google Sheets.\n\n\"At our scale, pacing is a discipline, not an afterthought. We have SLAs with clients that require within-5% budget delivery. Underdelivery means we refund media. Overdelivery means we absorb the overage.\"\n\nIn a typical week, approximately 30% of campaigns trigger at least one manual adjustment.\n\n\"That's 30% of campaigns requiring human intervention, across 40 clients, three times a day. That's a lot of touches.\"\n\nHas evaluated automated pacing tools including Quantcast, MediaMath's pacing algorithms, and a custom solution their tech team built. The custom solution was the most effective but required a full-time engineer to maintain.\n\n\"We built it, it worked, the engineer left, and we couldn't support it anymore. Went back to manual.\"\n\nWould pay for a managed pacing service that provides guaranteed delivery within SLA, with penalties on the vendor side for misses.\n\n\"I don't want software. I want a service that owns the outcome. If you're confident your tool works, take the delivery risk.\"\n\nConfirming on pain at scale. Challenging on software-only solutions — wants outcome-based pricing.",
        "summary": "Agency VP managing $120M in media across 40 clients where 30% of campaigns require manual pacing intervention three times daily. Tried a custom engineering solution that worked but wasn't maintainable. Key insight: at agency scale, the buyer wants outcome-based pricing with vendor-side delivery guarantees — not software licensing — because client SLA risk sits with the agency, not the tool."
    },
    {
        "id": "SES7",
        "study_id": "campaign-pacing-optimisation",
        "participant_id": "P7",
        "raw_notes": "P7 — Senior Campaign Manager, DTC brand, 180 employees. Recently churned from automated pacing within DV360 — switched back to manual pacing 4 months ago.\n\nUsed DV360's built-in automated pacing for 8 months. Turned it off after it caused two significant budget misallocation incidents.\n\n\"The first incident: DV360's algorithm shifted 60% of a campaign budget into display in the last 3 days of the month because display was hitting CPA targets. But our brand guidelines prohibit heavy display in the run-up to a product launch. The algorithm didn't know that context.\"\n\n\"The second incident: automated pacing accelerated spend when a competitor's PR crisis broke. Our ads appeared next to the crisis news coverage. The algorithm saw cheap CPMs and bought aggressively. Brand safety nightmare.\"\n\nHas gone back to manual pacing with daily check-ins.\n\n\"Manual is slower but it's controllable. I understand what it's doing and I can override it. The automated system did things I didn't understand and couldn't predict.\"\n\nWould consider automation again but with stronger constraint controls.\n\n\"I want to automate within guardrails I set. No more than X% budget shift per day, brand safety exclusion lists must be respected, specific placement types capped. If the tool can't honor those constraints, I don't want it.\"\n\nHis current manual process: Excel spreadsheet tracking planned vs. actual spend daily, with campaign-level delivery report pulled from DV360 each morning. Total time: 45-60 minutes per day.\n\nChallenging on fully autonomous pacing. Would accept automation with strict constraint parameters.",
        "summary": "Campaign Manager who churned from DV360's automated pacing after two costly incidents — a budget misallocation that violated brand guidelines, and an aggressive spend acceleration into brand-unsafe content. Has returned to manual pacing for control. Would re-adopt automation only with strict guardrails: per-day budget shift limits, brand safety constraint honoring, placement type caps. Key insight: autonomous pacing without constraint parameters creates unacceptable brand risk."
    },
    {
        "id": "SES8",
        "study_id": "campaign-pacing-optimisation",
        "participant_id": "P8",
        "raw_notes": "P8 — Head of Media Finance, media company, 350 employees. Responsible for reconciling planned vs. actual campaign spend across all media vendors.\n\nSpends approximately 3 days per month on pacing reconciliation work — comparing trafficking orders to vendor invoices to actual delivery reports. Finds discrepancies in 40-60% of campaigns that need manual investigation.\n\n\"Most discrepancies are small — within 3-5%. But I've had $80,000 overbilling incidents that took two weeks to resolve because the vendor's delivery report didn't match our tracking system.\"\n\nThe biggest reconciliation pain: multi-vendor campaign buys where a single campaign is split across three DSPs.\n\n\"Each DSP has a different flight date, a different reporting currency, and a different way of counting impressions. Reconciling a three-way split campaign is a 6-hour project every time.\"\n\nWould not describe herself as close to the pacing execution problem — that's the media team's problem. Her problem is downstream financial accuracy.\n\n\"I don't care how the pacing is managed, as long as I get clean delivery data that matches the invoice. That almost never happens.\"\n\nHer ask: an automated reconciliation tool that ingests delivery reports from multiple DSPs, normalizes them to a common standard, and flags discrepancies before invoices arrive.\n\n\"If I could catch a $50K discrepancy before it becomes an invoice dispute, that would save weeks of work.\"\n\nNo interest in pacing automation per se. Strong interest in financial reconciliation automation. Would pay $500-1,000/month.\n\nUncovers an adjacent market: financial reconciliation tooling for media buys is a distinct pain from pacing optimization.",
        "summary": "Media Finance Head spending 3 days/month reconciling planned vs. actual spend with discrepancies in 40-60% of campaigns, including an $80K overbilling incident. Her problem is downstream from pacing — financial reconciliation accuracy. Uncovers an adjacent market: financial reconciliation tooling for media buys at $500-1K/month, distinct from pacing optimization itself."
    },
    {
        "id": "SES9",
        "study_id": "campaign-pacing-optimisation",
        "participant_id": "P9",
        "raw_notes": "P9 — Performance Marketing Manager, e-commerce company, based in Dubai, operating across GCC and South Asia. Manages campaigns across multiple currencies (AED, SAR, PKR, INR).\n\nCurrency volatility compounds pacing complexity significantly. When a campaign is budgeted in AED but media is purchased in USD, a 3% currency move mid-flight changes the effective budget available without any campaign action.\n\n\"I've had campaigns overspend by 8% because the AED weakened against the dollar mid-month and I didn't catch it for three days.\"\n\nPlatform fragmentation in the region: Meta and Google are primary, but Snapchat is disproportionately important in Saudi Arabia, and regional platforms like Anghami have growing relevance. Each platform reports spend in different currencies.\n\n\"I'm looking at six dashboards in three currencies and trying to figure out if I'm on pace. There's no unified view.\"\n\nRamadan is the biggest pacing challenge: CPMs spike 3-5x in the two weeks before Ramadan, then drop immediately after.\n\n\"Every year I underestimate the Ramadan CPM spike. I set budgets based on historical data but the spike is getting more extreme each year. I always burn budget too fast in the run-up.\"\n\nHis manual solution: a Google Sheets model that converts all spending to USD daily, tracks against flight plan, and sends him a WhatsApp alert if any campaign is more than 10% off pace.\n\n\"It works but it's fragile. Any time a platform changes its reporting format my sheet breaks.\"\n\nConfirming on pacing pain in multi-currency, multi-platform environment. Challenging on most pacing tools being US-centric and not handling currency conversion.",
        "summary": "GCC-based marketer where pacing complexity is compounded by multi-currency exposure (AED budgeted, USD purchased) and seasonal Ramadan CPM spikes of 3-5x. Uses a fragile Google Sheets model with WhatsApp alerts as his pacing monitor. Most commercial pacing tools are US-centric and don't handle currency conversion or regional seasonal dynamics. Key insight: the international pacing problem has unique compounding factors that Western tools rarely address."
    },
    {
        "id": "SES10",
        "study_id": "campaign-pacing-optimisation",
        "participant_id": "P10",
        "raw_notes": "P10 — Programmatic Operations Manager, performance agency, 60 employees. Has built a custom pacing dashboard in Looker Studio connected to DV360, Meta, and Google Ads APIs.\n\nSpent 6 weeks building the dashboard after becoming frustrated that each platform's native reporting had different refresh rates and different pacing calculations. The custom dashboard normalizes spend data hourly, calculates expected vs. actual delivery, and sends Slack alerts when any campaign is more than 8% off pace.\n\n\"The dashboard tells me everything I need to know. The problem is what it tells me is always that something needs my attention. I'm still responding manually to every alert.\"\n\nCurrent limitation: the dashboard identifies pacing issues but the fix always requires a human to log into the platform and make the adjustment.\n\n\"I get the alert at 7pm. I log into DV360. I move the budget. I check again at 9pm. It's reactive, not proactive.\"\n\nHas explored using the DV360 API to automate the budget adjustment itself. Got 80% of the way there but stopped because of the risk of runaway automated adjustments.\n\n\"I don't trust automation to make budget decisions without a human review step. What if there's a data quality issue in the API and my automation accidentally moves $50,000?\"\n\nHis ideal system: automated detection + recommendation, with a one-click approval flow in Slack.\n\n\"If Slack tells me 'Campaign X needs $2,000 moved from placement A to placement B — approve?' and I can say yes in one tap, that's 80% of the manual work removed with human oversight preserved.\"\n\nStrongly confirming on pain. Has built the detection layer himself. Needs the human-in-loop automated execution layer.",
        "summary": "Programmatic Ops Manager who built a custom pacing dashboard detecting issues across DV360, Meta, and Google Ads — but fixes are always manual because he doesn't trust fully autonomous budget adjustments. His ideal workflow: automated detection + recommendation + one-click Slack approval for execution. This is the most specific product spec in the study: human-in-the-loop pacing automation, not fully autonomous adjustment."
    }
]

creative_testing_sessions = [
    {
        "id": "SES6",
        "study_id": "creative-testing-scale",
        "participant_id": "P6",
        "raw_notes": "P6 — Creative Director, CPG brand, 2,000 employees. Manages an in-house creative studio of 18 people and approves all A/B testing before campaigns launch.\n\nHas a formal creative testing framework: every campaign launches with a minimum of 4 creative variants across two dimensions (headline and visual). Tests run for a minimum of 2 weeks or 10,000 impressions per variant, whichever comes later.\n\n\"The framework is good on paper. In practice, the media team calls a winner after 3 days because they need to shift budget. I've had statistically meaningless results called 'winners' that then become the creative direction for the next quarter.\"\n\nHis creative team spends significant time producing variants that are then abandoned before reaching statistical significance.\n\n\"Last quarter we produced 47 creative variants for one campaign. 12 got meaningful impression volume. The other 35 were produced and discarded.\"\n\nCost of over-production: approximately $180K in creative production cost per year on variants that never get meaningful test volume.\n\n\"I'd rather do 10 variants properly than 47 variants poorly.\"\n\nThe measurement feedback loop is slow. Media team uses platform-native reporting; creative team uses a separate analytics tool; neither is the source of truth.\n\n\"It takes me 3 meetings to understand why a creative didn't perform. By then the campaign is over.\"\n\nWould pay for a tool that forces statistical discipline on the media team — minimum impression commitments before calling a winner.\n\n\"Make it harder to call a premature winner. That's the product I need.\"\n\nConfirming on over-production and premature winner-calling pain. Challenging on media team discipline and process enforcement.",
        "summary": "Creative Director running formal A/B testing frameworks but losing 35 of 47 creative variants to premature winner-calling before statistical significance is reached — an estimated $180K/year in wasted production. Key insight: the creative testing problem is not production volume, it's organizational behavior of calling winners prematurely. A tool that enforces statistical minimum thresholds would solve more than any production automation."
    },
    {
        "id": "SES7",
        "study_id": "creative-testing-scale",
        "participant_id": "P7",
        "raw_notes": "P7 — Head of Performance Creative, DTC food brand, 150 employees. Recently churned from Madgicx (creative analytics platform) after 8 months.\n\nLeft Madgicx because its creative analytics were only as good as the signal from Meta's API, which degraded post-iOS.\n\n\"We were paying $1,200/month for creative analytics that were telling us our best performer was a creative we'd already pulled because the organic content data told a different story.\"\n\nNow using a combination of Meta's Creative Insights natively and a custom spreadsheet tracking creative performance across organic social (Instagram), paid social (Meta), and email.\n\n\"I compare the same image or video across three channels. Usually the organic signal is a leading indicator for paid performance.\"\n\nHis workaround: test creative on organic Instagram (zero cost) before committing budget to paid testing.\n\n\"Instagram organic gives you 1,000-5,000 impressions within 24 hours on a good post. That's enough to get directional signal before you spend anything on paid testing.\"\n\nThe organic-before-paid workflow is not systematized. \"I'm doing this manually because I've noticed the pattern works. No one built a tool for it.\"\n\nWould pay for a tool that automates organic signal tracking and scoring as a pre-test filter before paid media.\n\n\"Show me which 5 of my 20 concepts have organic signal worth testing in paid. Save me from producing full-resolution paid ads for concepts that will fail.\"\n\nBudget: $500-800/month. Strongly challenging on MTA-dependent creative analytics. Bullish on organic-first testing signal as a viable approach.",
        "summary": "Performance creative lead who churned from Madgicx after iOS degraded its signal quality, and has since developed an organic-first testing methodology: test on Instagram organic (free) before committing paid budget. The workflow is manual and unsystematized — identifies a product opportunity in pre-paid creative signal scoring. Would pay $500-800/month for a tool that automates organic signal tracking as a paid testing filter."
    },
    {
        "id": "SES8",
        "study_id": "creative-testing-scale",
        "participant_id": "P8",
        "raw_notes": "P8 — Head of Finance, consumer software company, 250 employees. Approves all creative production spend over $5,000.\n\nHas been asked to approve creative testing budgets three times in the last 18 months and each time has pushed back on the lack of a measurement plan.\n\n\"Marketing asks for $40,000 to produce 20 video variants for A/B testing. I ask: what are we trying to learn, and how will we know if the test succeeded? Usually there's no good answer.\"\n\nHis core objection: creative production is the highest-cost input in the testing process, but it's approved before anyone has confirmed what they're measuring.\n\n\"You're committing the biggest cost item before you've committed the measurement framework. That's backwards.\"\n\nHas asked the marketing team to implement a pre-production test brief that specifies: (1) the hypothesis being tested, (2) the metric for success, (3) the minimum impression volume for statistical significance, and (4) what they'll do with the result.\n\n\"Four questions. If you can't answer them before production, you shouldn't be producing.\"\n\nThree of the last four creative test proposals have been rejected at pre-production stage when the brief exercise revealed the team didn't have clear answers.\n\n\"We saved $90,000 in production costs on concepts that shouldn't have been tested in the first place.\"\n\nWould approve creative testing tools only if they include a mandatory pre-production planning layer.\n\n\"I don't want a tool that helps you produce more creative faster. I want a tool that helps you produce better creative with a plan.\"\n\nChallenging on creative volume as the metric. Strong advocate for pre-production discipline.",
        "summary": "Head of Finance who has institutionalized a pre-production test brief (hypothesis, success metric, minimum impression volume, decision criteria) that has blocked $90K in production cost on untestable concepts. His frame is the inverse of most creative testing tool pitches: the problem isn't production volume, it's pre-production discipline — and any tool that enables faster production without better planning makes the problem worse."
    },
    {
        "id": "SES9",
        "study_id": "creative-testing-scale",
        "participant_id": "P9",
        "raw_notes": "P9 — Performance Marketing Lead, fashion brand, based in Stockholm, 350 employees. Manages creative testing across 5 EU markets in 3 languages.\n\nThe creative testing challenge in EU markets: each market requires language localization, and localized creative must go through legal review for regulatory compliance (particularly claims language involving sustainability or discounting).\n\n\"By the time we have a statistically significant winner in a multilingual test, the campaign is 60% over. We're optimizing for the last 40% of the campaign flight.\"\n\nHer workaround: run tests in English first in the UK, then localize the winner into local languages for the remaining markets.\n\n\"We accept lower performance in the early campaign period in non-English markets in exchange for statistical confidence in what we're testing.\"\n\nThe quality problem with this approach: UK creative doesn't always translate culturally.\n\n\"We've had 'winning' English creatives perform 40% below benchmark when localized to Swedish or Danish because the cultural reference didn't land.\"\n\nAlso manages a creative knowledge base in Notion — documenting what worked and why across campaigns. This was started after a team member asked 'didn't we already test this?' about a concept from 18 months ago.\n\n\"We'd run essentially the same test twice with the same result. Because nobody documented the first one.\"\n\nConfirming on multilingual testing complexity and knowledge management pain. Challenging on single-language testing approaches being applicable to multi-market EU operations.",
        "summary": "EU Performance Marketing Lead in Stockholm where multilingual creative testing takes 4-6x longer than single-language markets — meaning most statistical winners are only identified after 60% of the campaign has run. Runs an English-first testing strategy that risks cultural translation failures. Has built a Notion knowledge base to prevent re-testing the same concepts. Key insight: multi-market creative testing is a fundamental timing problem that undermines the value of testing insights."
    },
    {
        "id": "SES10",
        "study_id": "creative-testing-scale",
        "participant_id": "P10",
        "raw_notes": "P10 — Performance Marketing Manager, B2B SaaS, 200 employees. Has built a creative testing tracker in Airtable that logs every test, result, and learning across the last 3 years.\n\nMaintains 847 records in the Airtable base — one row per creative test, with fields for: variant type, hypothesis, platform, audience, impression volume, result, statistical significance, and 'learning' (qualitative). Updates it personally after every test.\n\n\"It takes me about 20 minutes per test to log. It's the most valuable 20 minutes I spend.\"\n\nThe base has paid off: when a junior team member proposed a headline format test that was nearly identical to one run 18 months ago, she found it in Airtable and shared the results.\n\n\"We would have spent $15,000 producing variants for a test we already knew the answer to.\"\n\nThe limitation: the knowledge lives in her head and her Airtable. When she's on holiday, no one uses it.\n\n\"The institutional memory is personalized, not institutionalized. That's fragile.\"\n\nHas attempted to get the team to contribute to the base but failed.\n\n\"Nobody wants to do the 20-minute logging after a campaign. It feels like admin. It needs to be automatic.\"\n\nHer ideal tool: something that connects to the ad platforms, automatically captures test results, and prompts for qualitative annotations at campaign end — without requiring manual data entry.\n\n\"If the results flow in automatically and I just have to answer 3 questions about what we learned, the whole team would do it.\"\n\nStrongly confirming on knowledge management pain. Has the most systematic approach to creative testing knowledge of any participant. Identifies a clear product gap.\n\n\"There are creative analytics tools and there are project management tools. Nobody has built the intersection.\"",
        "summary": "Performance Marketing Manager who has manually maintained an 847-record Airtable creative testing database for 3 years — saving $15K by catching a duplicate test. The system is fragile because it depends on her personal 20-minute post-test logging; nobody else uses it. Identifies the product gap: an automated creative test results capture tool that pulls platform data and prompts for qualitative annotations, replacing manual logging with a 3-question prompt."
    }
]

frequency_sessions = [
    {
        "id": "SES6",
        "study_id": "cross-channel-frequency",
        "participant_id": "P6",
        "raw_notes": "P6 — VP Programmatic, enterprise media company, 6,000 employees. Manages cross-channel frequency for a portfolio of 25 clients including several Fortune 500 brands.\n\nHas access to enterprise identity resolution tools: LiveRamp IdentityLink and The Trade Desk's Unified ID 2.0. Also has direct publisher agreements with clean room access to YouTube and Meta for cross-platform frequency validation studies.\n\n\"We run quarterly frequency audits for our top clients. We match exposure logs from our DSP with publisher-provided reach data to quantify how much duplication exists. The answer is always: a lot more than anyone expected.\"\n\nOn a recent CPG client campaign: 42% of people who saw the campaign saw it more than 10 times across channels in a 7-day window. 18% saw it more than 20 times.\n\n\"The client was running display on DV360, video on YouTube direct, and social on Meta. Each channel thought it was running at 3+ frequency. Combined, some users were getting hit 25 times a week.\"\n\nThe mitigation: cross-channel suppression using a shared user ID list. Users who exceeded the frequency threshold in the DSP were suppressed in Meta using a custom audience exclusion.\n\n\"It works but it's a 24-hour lag minimum. If someone hits frequency cap at 10am, they might see 3-4 more ads before the suppression propagates.\"\n\nWalled garden data access is the fundamental barrier.\n\n\"Meta will tell you what happened inside Meta. They won't let you see how that intersects with what's happening outside Meta. That's the wall you can't scale.\"\n\nConfirming on frequency problem at enterprise scale. Skeptical that any non-walled-garden solution can provide real cross-platform frequency management without identity resolution infrastructure.",
        "summary": "Enterprise VP Programmatic running quarterly cross-channel frequency audits that consistently show 42%+ of campaign-reached users exceeding 10-frequency thresholds. Uses shared user ID suppression as a mitigation but faces minimum 24-hour propagation lag. Key insight: the enterprise already knows the frequency problem is severe and has partial mitigations — the unresolved gap is real-time cross-platform suppression without walled garden cooperation."
    },
    {
        "id": "SES7",
        "study_id": "cross-channel-frequency",
        "participant_id": "P7",
        "raw_notes": "P7 — Head of Paid Media, DTC brand, 180 employees. Churned from The Trade Desk 6 months ago for their primary prospecting and moved spend to Meta only.\n\nLeft TTD because cross-channel frequency management between TTD and Meta was impossible to coordinate.\n\n\"I was running prospecting in TTD and retargeting in Meta. I had no way to know if the same person was seeing both. My frequency cap in TTD meant nothing because it didn't account for Meta impressions.\"\n\nConsolidated all spend onto Meta to control frequency within one walled garden.\n\n\"Yes, I'm leaving reach on the table by not using display and video. But at least I know my frequency isn't out of control.\"\n\nThe consolidation improved a key brand health metric: their post-purchase survey now shows a 15% reduction in 'ad fatigue' mentions compared to pre-consolidation.\n\n\"The data isn't perfect but it's directional. Consolidating into one platform reduced frequency overexposure even though total reach went down.\"\n\nWould consider re-expanding to multi-channel if cross-platform frequency management was solvable.\n\n\"The day someone shows me a credible cross-platform frequency cap that actually works in real time, I'll expand back to display.\"\n\nHis current Meta frequency target: 3-4 per week per person. \"Below 3 and brand recall suffers. Above 4 and we start seeing negative sentiment in comments. That band is narrow and easy to blow through.\"\n\nChallenging on multi-channel frequency management as currently solvable. Has made the pragmatic choice to consolidate channels rather than manage frequency across them.",
        "summary": "Head of Paid Media who deliberately consolidated from multi-channel to Meta-only to achieve frequency control — accepting lower reach in exchange for manageable frequency. Post-purchase survey shows 15% reduction in ad fatigue complaints post-consolidation. Provides the starkest evidence of the problem's severity: a brand choosing channel consolidation as the solution to frequency management failure. Would re-expand if real-time cross-platform frequency capping existed."
    },
    {
        "id": "SES8",
        "study_id": "cross-channel-frequency",
        "participant_id": "P8",
        "raw_notes": "P8 — CMO, mid-market consumer brand, 300 employees. Was alerted to frequency problems by brand sentiment monitoring rather than ad tech reporting.\n\nFirst became aware of frequency overexposure when their social listening tool flagged a spike in comments like 'I keep seeing this ad everywhere' and 'please make this ad stop.' The spike coincided with a campaign that was within normal frequency caps on every individual platform.\n\n\"The platforms all told me I was running at 3-4 frequency. My social listening tool was telling me consumers were complaining about seeing the ad 'everywhere.' Those two facts can both be true if the frequency is combined across platforms.\"\n\nHas since made brand health monitoring a leading indicator for ad frequency problems.\n\n\"Before I had this data, frequency was a media operations metric. Now it's a brand health metric. If ad fatigue mentions go up, something is wrong with our frequency management.\"\n\nThe operational challenge: by the time brand health metrics show frequency fatigue, the damage is done.\n\n\"It takes 2-3 weeks for consumer complaints to peak after frequency overexposure begins. The campaign is often 70% over by then.\"\n\nWould pay for early-warning signals that predict brand fatigue before it shows up in qualitative research.\n\n\"If you could tell me 'you're trending toward frequency fatigue in the 18-34 demographic, based on engagement rate decay' before I see it in sentiment, that would be worth a lot.\"\n\nBudget: $2-3K/month for a brand safety/frequency monitoring product that integrated with her social listening stack.\n\nConfirming on frequency fatigue as a brand health issue. Challenging on in-platform frequency metrics being an adequate early warning signal.",
        "summary": "CMO who first identified cross-platform frequency overexposure through consumer sentiment data rather than ad platform metrics — which all showed normal levels. Has repositioned frequency management as a brand health metric. Key insight: the right frequency signal for a CMO buyer is engagement rate decay and sentiment monitoring as a leading indicator, not in-platform frequency caps as a lagging constraint."
    },
    {
        "id": "SES9",
        "study_id": "cross-channel-frequency",
        "participant_id": "P9",
        "raw_notes": "P9 — Performance Marketing Manager, travel company, based in Singapore, operating across APAC. Manages display, video, and social across 8 markets.\n\nThe frequency management challenge in APAC: platform mix varies significantly by market. Japan heavy on Yahoo Japan and Line; Southeast Asia heavy on TikTok and Shopee; Australia and NZ similar to Western markets.\n\n\"In Japan, I can't even see my frequency across Line and Yahoo Japan because neither provides cross-platform data. I'm flying blind on frequency for 30% of my regional budget.\"\n\nCultural dimension: ad tolerance varies by market. In Japan, consumers tolerate higher advertising frequency than in Australia or Singapore.\n\n\"What feels like overexposure in Sydney is considered normal in Tokyo. Applying a single frequency cap across the region is wrong, but I don't have the infrastructure to manage market-specific caps.\"\n\nHer practical solution: platform-specific frequency caps set conservatively, and then a manual creative rotation every 10 days regardless of frequency data.\n\n\"I rotate creative every 10 days whether or not the frequency data says I should. It's a proxy for freshness that doesn't depend on data I don't have.\"\n\nThe creative rotation workaround has a cost: 6-8 creative assets per campaign per market to support the rotation. At her scale (8 markets), that's 48-64 assets per campaign cycle.\n\n\"The creative production cost of my frequency management workaround is probably $30,000-40,000 a year.\"\n\nConfirming on cross-platform frequency gap in APAC. Challenging on market-agnostic frequency solutions.",
        "summary": "APAC-based marketer managing 8 markets where platform mix varies so significantly that cross-platform frequency is unmeasurable in some markets (Japan: Line + Yahoo Japan). Uses creative rotation every 10 days as a proxy frequency management workaround at an estimated $30-40K/year in creative production cost. Key insight: frequency tolerance varies culturally across markets, making universal frequency caps inappropriate for multi-market APAC operations."
    },
    {
        "id": "SES10",
        "study_id": "cross-channel-frequency",
        "participant_id": "P10",
        "raw_notes": "P10 — Programmatic Trader, performance agency, 70 employees. Has built a custom cross-channel frequency estimation model using aggregate reach and frequency data from multiple platforms.\n\nSpent 3 months building a probabilistic model that estimates cross-platform frequency overlap. Inputs: reach curves from DV360, reach curves from Meta, and audience overlap assumptions based on Comscore panel data. Output: an estimated frequency distribution showing what % of the total audience is likely to have seen the campaign 1x, 2-5x, 6-10x, 10x+.\n\n\"It's not precise. It's an estimate. But it's the best information available without an identity graph, and it's good enough to make budget decisions.\"\n\nUses the model to set platform budgets: if the model shows excessive predicted overlap between DV360 and Meta for the target audience, he reallocates budget to a lower-overlap channel.\n\n\"The model has changed how I think about the problem. Frequency management isn't a technology problem first — it's a planning problem. If you select channels with lower audience overlap upfront, you spend less time trying to suppress frequency mid-campaign.\"\n\nHas tried to explain this model to clients and been met with skepticism.\n\n\"Clients want a precise number. 'We're running at 4.3 frequency across all channels.' I can't give them that. I can give them a probability distribution. Most clients aren't comfortable with probabilistic thinking.\"\n\nWould consider commercializing the model if a vendor offered a revenue share or acquisition.\n\n\"I've built the thing. I don't want to run a software company. If someone wanted to turn this into a product, I'd talk.\"\n\nStrongly confirming on the frequency problem. Has built a planning-layer solution that reframes the problem. Would consider commercializing if the right partnership emerged.",
        "summary": "Programmatic trader who built a probabilistic cross-channel frequency estimation model — reframing frequency management from a mid-campaign suppression problem to an upfront channel planning problem. The model works but is hard to communicate to clients who expect precise numbers rather than probability distributions. Open to acquisition or revenue-share conversations. Key insight: treating frequency management as a planning problem (channel selection based on predicted overlap) rather than a runtime suppression problem is a fundamentally different and more tractable approach."
    }
]

updates = [
    ("adtech_study.json", adtech_sessions),
    ("audience_segmentation.json", audience_sessions),
    ("attribution_modelling.json", attribution_sessions),
    ("campaign_pacing.json", pacing_sessions),
    ("creative_testing.json", creative_testing_sessions),
    ("frequency_management.json", frequency_sessions),
]

for filename, new_sessions in updates:
    path = f"data/{filename}"
    with open(path) as f:
        data = json.load(f)
    data["sessions"].extend(new_sessions)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"OK {filename}: {len(data['sessions'])} sessions")

print("Done.")
